# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfinstall
    jobs:
      - job: infracostazuredemo
        steps:
          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'Alpesh-Personal-Azure'
          #     scriptType: bash
          #     scriptLocation: inlineScript
          #     inlineScript: 'az group list -o table'
          - task: TerraformInstaller@0
            displayName: terraform install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'init'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Alpesh-Personal-Azure'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'terraform plan -out tfplan.binary'

               
          # - script: |
          #     curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          #     tar xzf infracost-linux-amd64.tar.gz -C /tmp
          #     mv /tmp/infracost-linux-amd64 /usr/local/bin/infracost
          #     infracost --version
          #   displayName: Check infracost version
          # - script: |
          #     terraform apply 
          #     terraform show -json tfplan.binary > plan.json
          #     infracost breakdown --show-skipped --path plan.json 
          #     terraform apply
          #   displayName: Cost Estimation
          #   env:
          #     INFRACOST_API_KEY: $(INFRACOST_API_KEY)

