# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfinstall
    jobs:
      - job: infracostazuredemo
        steps:
          - task: TerraformInstaller@0
            displayName: terraform install
            inputs:
              terraformVersion: 'latest'
               


          - task: TerraformTaskV3@3
            displayName: terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Alpesh-Personal-Azure'
              backendAzureRmResourceGroupName: 'EIC-DevOps-RG'
              backendAzureRmStorageAccountName: tfstate
              backendAzureRmContainerName: tfstate
              backendAzureRmKey: tfstate
          - task: TerraformTaskV3@3
            displayName: terraform plan
            inputs:
              provider: 'azurerm'
              command: 'custom'
              customCommand: 'plan'
              outputTo: 'console'
              backendServiceArm: 'Alpesh-Personal-Azure'
              backendAzureRmResourceGroupName: 'EIC-DevOps-RG'
              backendAzureRmStorageAccountName: tfstate
              backendAzureRmContainerName: tfstate
              backendAzureRmKey: tfstate
              environmentServiceNameAzureRM: 'Alpesh-Personal-Azure'
              
          - script: |
              curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
              tar xzf infracost-linux-amd64.tar.gz -C /tmp
              mv /tmp/infracost-linux-amd64 /usr/local/bin/infracost
              infracost --version
            displayName: Check infracost version









          # - script: |
          #     curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          #     tar xzf infracost-linux-amd64.tar.gz -C /tmp
          #     mv /tmp/infracost-linux-amd64 /usr/local/bin/infracost
          #     infracost --version
          #   displayName: Check infracost version
          # - script: |
          #     az login
          #     terraform init

  
          #   displayName: Setup az account
          # - script: |
          #     terraform show -json tfplan.binary > plan.json
          #     infracost breakdown --show-skipped --path plan.json 
          #   displayName: Cost Estimation
          #   env:
          #     INFRACOST_API_KEY: $(INFRACOST_API_KEY)

          # - task: ManualValidation@0
          #   timeoutInMinutes: 2
          #   inputs:
          #    notifyUsers: 'jagrutigour1799@gmail.com'
          #    instructions: 'Hi please apply to approve'

            
