# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfinstall
    jobs:
      - job: infracostazuredemo
        steps:
          - task: TerraformInstaller@0
            displayName: terraform install
            inputs:
              terraformVersion: 'latest'
          - script: |
              terraform -version
              terraform init
              terraform plan -out tfplan.binary
              sudo apt-get update
              sudo apt-get install lynx
            displayName: terraform validation
            env:
              azureSubscription: $(azureSubscription)
          - script: |
              curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
              tar xzf infracost-linux-amd64.tar.gz -C /tmp
              mv /tmp/infracost-linux-amd64 /usr/local/bin/infracost
              infracost --version
            displayName: Check infracost version
          - script: |
              terraform show -json tfplan.binary > plan.json
              infracost breakdown --path plan.json 
            displayName: Cost Estimation
            env:
              INFRACOST_API_KEY: $(INFRACOST_API_KEY)
              azureSubscription: $(azureSubscription)